name: push scripts to github pages

on:
  push:
    branches: [ "main" ]
  schedule:
  - cron: "0 2 * * 3"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: create artifact folder
        run: |
          mkdir output
          cp *.js output/
          cp *.html output/
            
      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
